export enum ErrorCode {
    BAD_REQUEST = 'BAD_REQUEST',
    NOT_FOUND = 'NOT_FOUND',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    PLAN_LIMIT_REACHED = 'PLAN_LIMIT_REACHED',
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
    CONTENT_VALIDATION_FAILED = 'CONTENT_VALIDATION_FAILED',
}
