/**
 * Source of the transcript
 */
export type TranscriptSourceType = 'human_captions' | 'auto_captions' | 'stt'

/**
 * Information about an available caption track
 */
export interface CaptionTrack {
    /** Language code (e.g., 'en', 'ru', 'es') */
    language: string

    /** Human-readable language name */
    languageName: string

    /** Whether this is auto-generated */
    isAutoGenerated: boolean

    /** Format of the captions (vtt, srv1, etc.) */
    format?: string
}

/**
 * Result of fetching available captions
 */
export interface AvailableCaptionsResult {
    /** Video ID */
    videoId: string

    /** Video title */
    title?: string

    /** Video duration in seconds */
    durationSec?: number

    /** Human-created captions */
    humanCaptions: CaptionTrack[]

    /** Auto-generated captions */
    autoCaptions: CaptionTrack[]

    /** Whether any captions are available */
    hasCaptions: boolean
}

/**
 * Result of downloading captions
 */
export interface DownloadCaptionsResult {
    /** Video ID */
    videoId: string

    /** Language code of the downloaded captions */
    language: string

    /** Source type */
    source: TranscriptSourceType

    /** Format of the captions */
    format: 'vtt' | 'srt' | 'text'

    /** Raw caption content */
    content: string
}

/**
 * Options for downloading captions
 */
export interface DownloadCaptionsOptions {
    /** Preferred language code (e.g., 'en', 'ru') */
    preferredLanguage?: string

    /** Prefer human-created captions over auto-generated */
    preferHuman?: boolean

    /** Preferred format */
    format?: 'vtt' | 'srt'
}

/**
 * Error types for transcript provider
 */
export type TranscriptProviderErrorCode =
    | 'VIDEO_UNAVAILABLE'
    | 'VIDEO_PRIVATE'
    | 'VIDEO_AGE_RESTRICTED'
    | 'VIDEO_REGION_BLOCKED'
    | 'NO_CAPTIONS_AVAILABLE'
    | 'CAPTION_DOWNLOAD_FAILED'
    | 'YTDLP_ERROR'
    | 'UNKNOWN_ERROR'

/**
 * Service interface for fetching YouTube video transcripts/captions
 */
export interface ITranscriptProviderService {
    /**
     * Get list of available captions for a video
     */
    getAvailableCaptions(videoId: string): Promise<AvailableCaptionsResult>

    /**
     * Download captions for a video with fallback strategy:
     * 1. Human captions in preferred language
     * 2. Human captions in any language
     * 3. Auto captions in preferred language
     * 4. Auto captions in any language
     *
     * Throws if no captions are available
     */
    downloadCaptions(videoId: string, options?: DownloadCaptionsOptions): Promise<DownloadCaptionsResult>

    /**
     * Check if video is accessible (not private, age-restricted, etc.)
     */
    isVideoAccessible(videoId: string): Promise<boolean>
}

